// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgtypes.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgtypes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* MessageType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgtypes_2eproto() {
  protobuf_AddDesc_msgtypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgtypes.proto");
  GOOGLE_CHECK(file != NULL);
  MessageType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgtypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_msgtypes_2eproto() {
}

void protobuf_AddDesc_msgtypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016msgtypes.proto*\327\001\n\013MessageType\022\r\n\tACTO"
    "R_REQ\020\001\022\017\n\013ACTOR_REPLY\020\002\022\021\n\rCONTAINER_RE"
    "Q\020\003\022\023\n\017CONTAINER_REPLY\020\004\022\r\n\tPACKET_IN\020\t\022"
    "\016\n\nPACKET_OUT\020\n\022\t\n\005USER1\020\013\022\t\n\005USER2\020\014\022\t\n"
    "\005USER3\020\r\022\t\n\005USER4\020\016\022\t\n\005USER5\020\017\022\t\n\005USER6\020"
    "\020\022\t\n\005USER7\020\021\022\t\n\005USER8\020\022\022\t\n\005USER9\020\023", 234);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgtypes.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgtypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgtypes_2eproto {
  StaticDescriptorInitializer_msgtypes_2eproto() {
    protobuf_AddDesc_msgtypes_2eproto();
  }
} static_descriptor_initializer_msgtypes_2eproto_;
const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageType_descriptor_;
}
bool MessageType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
