// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgtypes.proto

#ifndef PROTOBUF_msgtypes_2eproto__INCLUDED
#define PROTOBUF_msgtypes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msgtypes_2eproto();
void protobuf_AssignDesc_msgtypes_2eproto();
void protobuf_ShutdownFile_msgtypes_2eproto();


enum MessageType {
  ACTOR_REQ = 1,
  ACTOR_REPLY = 2,
  CONTAINER_REQ = 3,
  CONTAINER_REPLY = 4,
  PACKET_IN = 9,
  PACKET_OUT = 10,
  USER1 = 11,
  USER2 = 12,
  USER3 = 13,
  USER4 = 14,
  USER5 = 15,
  USER6 = 16,
  USER7 = 17,
  USER8 = 18,
  USER9 = 19
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = ACTOR_REQ;
const MessageType MessageType_MAX = USER9;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageType>() {
  return ::MessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgtypes_2eproto__INCLUDED
