# OmniOS Driver Makefile
#
# AUTHOR: Chen Tian @ Samsung, 
#
# Date: Mar 7, 2011 

USER_INCLUDES += ../../servers/mptable


APP_NAME = e1000

include ../drivers.mk


manifest.bin:
	../../tools/bcl/bfc c huff ./manifest.xml ./manifest.bin



